name: ChrisMissal.com
description: The online portfolio, blog, and resume of Chris Missal.
url: http://chrismissal.com
highlighter: pygments
username: ChrisMissal
markdown: kramdown

scripts:
  instafeed: /js/instafeed.min.js